# Generated by Django 4.1.1 on 2022-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledetailpage',
            old_name='caption',
            new_name='credits',
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
