# Generated by Django 4.1.1 on 2022-09-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_caption_articledetailpage_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetailpage',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='articledetailpage',
            name='source_url',
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BigHeroArticleDetailPage',
            fields=[
                ('articledetailpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.articledetailpage')),
                ('credits', models.CharField(blank=True, help_text='Enter the source name for this image', max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articledetailpage',),
        ),
    ]
